steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/golang:1.12.3-alpine3.9, -f, golang:1.12.3-alpine3.9.Dockerfile, '.']
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/alpine:3.9, -f, alpine:3.9.Dockerfile, '.']
  waitFor: ['-']

images:
- gcr.io/$PROJECT_ID/golang:1.12.3-alpine3.9
- gcr.io/$PROJECT_ID/alpine:3.9
