steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/golang:1.12.3-alpine3.9, -f, golang:1.12.3-alpine3.9.Dockerfile, '.']

images:
- gcr.io/$PROJECT_ID/golang:1.12.3-alpine3.9
