steps:
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, gcr.io/$PROJECT_ID/alpine, -f, alpine.Dockerfile, .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/alpine:3.10.2', -f, 'alpine:3.10.2.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/alpine:3.10', -f, 'alpine:3.10.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/filebrowser:v2.0.14', -f, 'filebrowser:v2.0.14.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/golang:1.13.1-alpine', -f, 'golang:1.13.1-alpine.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/golang:1.13.1-alpine3.10', -f, 'golang:1.13.1-alpine3.10.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/golang:alpine', -f, 'golang:alpine.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/golang:alpine3.10', -f, 'golang:alpine3.10.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/$PROJECT_ID/php:7.3.10-fpm-alpine', -f, 'php:7.3.10-fpm-alpine.Dockerfile',
    .]
  waitFor: ['-']
images:
- gcr.io/$PROJECT_ID/alpine
- gcr.io/$PROJECT_ID/alpine:3.10.2
- gcr.io/$PROJECT_ID/alpine:3.10
- gcr.io/$PROJECT_ID/filebrowser:v2.0.14
- gcr.io/$PROJECT_ID/golang:1.13.1-alpine
- gcr.io/$PROJECT_ID/golang:1.13.1-alpine3.10
- gcr.io/$PROJECT_ID/golang:alpine
- gcr.io/$PROJECT_ID/golang:alpine3.10
- gcr.io/$PROJECT_ID/php:7.3.10-fpm-alpine
