steps:
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, gcr.io/moonrhythm-containers/alpine, -f, alpine.Dockerfile,
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/alpine:3.10.3', -f, 'alpine:3.10.3.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/alpine:3.10', -f, 'alpine:3.10.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/filebrowser:v2.0.14', -f,
    'filebrowser:v2.0.14.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.12-alpine', -f,
    'golang:1.12-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13-alpine', -f,
    'golang:1.13-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13.4-alpine', -f,
    'golang:1.13.4-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13.4-alpine3.10',
    -f, 'golang:1.13.4-alpine3.10.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:alpine', -f, 'golang:alpine.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:alpine3.10', -f,
    'golang:alpine3.10.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/php:7.3.11-fpm-alpine',
    -f, 'php:7.3.11-fpm-alpine.Dockerfile', .]
  waitFor: ['-']
images:
- gcr.io/moonrhythm-containers/alpine
- gcr.io/moonrhythm-containers/alpine:3.10.3
- gcr.io/moonrhythm-containers/alpine:3.10
- gcr.io/moonrhythm-containers/filebrowser:v2.0.14
- gcr.io/moonrhythm-containers/golang:1.12-alpine
- gcr.io/moonrhythm-containers/golang:1.13-alpine
- gcr.io/moonrhythm-containers/golang:1.13.4-alpine
- gcr.io/moonrhythm-containers/golang:1.13.4-alpine3.10
- gcr.io/moonrhythm-containers/golang:alpine
- gcr.io/moonrhythm-containers/golang:alpine3.10
- gcr.io/moonrhythm-containers/php:7.3.11-fpm-alpine
