steps:
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, gcr.io/moonrhythm-containers/alpine, -f, alpine.Dockerfile,
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/alpine:3.10', -f, 'alpine:3.10.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/alpine:3.11', -f, 'alpine:3.11.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.12-alpine', -f,
    'golang:1.12-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13-alpine', -f,
    'golang:1.13-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13.5-alpine', -f,
    'golang:1.13.5-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:1.13.5-alpine3.11',
    -f, 'golang:1.13.5-alpine3.11.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:alpine', -f, 'golang:alpine.Dockerfile',
    .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:alpine3.10', -f,
    'golang:alpine3.10.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/golang:alpine3.11', -f,
    'golang:alpine3.11.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/php:7.3.13-apache', -f,
    'php:7.3.13-apache.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/php:7.3.13-fpm-alpine',
    -f, 'php:7.3.13-fpm-alpine.Dockerfile', .]
  waitFor: ['-']
- name: gcr.io/cloud-builders/docker
  args: [build, --pull, -t, 'gcr.io/moonrhythm-containers/php:7.4.1-apache', -f, 'php:7.4.1-apache.Dockerfile',
    .]
  waitFor: ['-']
images:
- gcr.io/moonrhythm-containers/alpine
- gcr.io/moonrhythm-containers/alpine:3.10
- gcr.io/moonrhythm-containers/alpine:3.11
- gcr.io/moonrhythm-containers/golang:1.12-alpine
- gcr.io/moonrhythm-containers/golang:1.13-alpine
- gcr.io/moonrhythm-containers/golang:1.13.5-alpine
- gcr.io/moonrhythm-containers/golang:1.13.5-alpine3.11
- gcr.io/moonrhythm-containers/golang:alpine
- gcr.io/moonrhythm-containers/golang:alpine3.10
- gcr.io/moonrhythm-containers/golang:alpine3.11
- gcr.io/moonrhythm-containers/php:7.3.13-apache
- gcr.io/moonrhythm-containers/php:7.3.13-fpm-alpine
- gcr.io/moonrhythm-containers/php:7.4.1-apache
